### ISSUE TITLE
Error  Class 'App\libraries\AuthLibrary' not found

### ISSUE THREAD

**Issue by EsoCoding** [GeekLabsUK/SimpleAuth#1]
In Auth Controller `use App\libraries\AuthLibrary` should be `use App\Libraries\AuthLibrary`.

Another error which is the same as above but then in AuthLibrary is `use App\libraries\SendEmail` should be 'use App\Libraries\SendEmail' 

Multiple setcookie function had a  ,  at the end of each array should be removed. So it should look like:
        
```
       setcookie(
            "remember",
            $token,
            $expires,
            $this->AppConfig->cookiePath,
            $this->AppConfig->cookieDomain,
            $this->AppConfig->cookieSecure,
            $this->AppConfig->cookieHTTPOnly
        );
```

Also i got the error: `validateUser is not a valid rule.` Don't found out yet why, but it returned this error.

And then there is something wrong with the filters, can't figure out what exactly just yet. But it says `auth filter must have a matching alias defined. `

**Comment by HermesTrismegistus** [comment]
In Auth Controller `use App\libraries\AuthLibrary` should be `use App\Libraries\AuthLibrary`.

Another error which is the same as above but then in AuthLibrary is `use App\libraries\SendEmail` should be 'use App\Libraries\SendEmail' 

In setcookie, a ',' at the end should be removed. 

And then there is something wrong with the filters, can't figure out what exactly just yet.

**Comment by HermesTrismegistus** [comment]
In Auth Controller `use App\libraries\AuthLibrary` should be `use App\Libraries\AuthLibrary`.

Another error which is the same as above but then in AuthLibrary is `use App\libraries\SendEmail` should be 'use App\Libraries\SendEmail' 

In setcookie, a ',' at the end should be removed. 

And then there is something wrong with the filters, can't figure out what exactly just yet.

**Comment by kidino** [comment]
I submitted a pull request for this.

**Comment by daltonmart** [comment]
HI!
Also i got the error: **validateUser** is not a valid rule. Don't found out yet why, but it returned this error.

And then there is something wrong with the filters, can't figure out what exactly just yet. But it says auth filter must have a matching alias defined. 

-----------------------------------------------------------------------------------------------------------------------
Debug trace:
APPPATH/Controllers/Auth.php : line 75 — CodeIgniter\Controller->validate ( arguments )

$rules 	
Array (
    [email] => required|valid_email
    [password] => required|min_length[6]|max_length[255]|validateUser[email,password]
)

$messages
Array
(
    [password] => Array
        (
            [validateUser] => Email or Password do not match
        )

)

**Comment by daltonmart** [comment]
HI i'm fix the **auth filter must have a matching alias defined**
adding in app\Config\Filter.php at public $aliases 
**'auth'     => \App\Filters\Auth::class,**	

Example
	public $aliases = [
		'csrf'     => CSRF::class,
		'toolbar'  => DebugToolbar::class,
		'honeypot' => Honeypot::class,
                'auth'     => \App\Filters\Auth::class,	
	];
