### ISSUE TITLE
Superadmin Routes 404

### ISSUE THREAD

**Issue by andrenalin282** [GeekLabsUK/SimpleAuth#4]
Hi,

in Routes.php line 58
$routes->get('superadmin', 'superadmin::index'); // SUPER ADMIN DASHBOARD

should be
$routes->get('superadmin', '**Superadmin**::index'); // SUPER ADMIN DASHBOARD

Controller uppercase... You get 404

br

**Comment by GeekLabsUK** [comment]
fixed with latest commit.
