### ISSUE TITLE
Verify logged in status on all pages

### ISSUE THREAD

**Issue by MarcPinnell** [GeekLabsUK/SimpleAuth#5]
I am new to this and trying to wrap my head around how to make sure users are logged in on EVERY request. Having issues where the session will time out, but you can still select an item from the menu and the page will load. When this happens the Logged In indicator then shows "Log In" instead of profile info.
This is an internal app, so there is no /admin/ or anything. All requests at the root level should be auth'd

**Comment by GeekLabsUK** [comment]
i'm not quite sure what your asking - This is an internal app, so there is no /admin/ or anything. All requests at the root level should be auth'd

any app that needs users to login will need an admin section to the site. Basically a login page which is the roadblock to the next authorised page which would be the admin, or whatever else it is your doing there.

All of the auth checking is done via filters on the routes so to ensure your users are logged in you simple add something like 
`$routes->group('', ['filter' => 'auth:Role,1'], function ($routes) {

	$routes->get('admin', 'admin::index'); // ADMIN DASHBOARD
	$routes->match(['get', 'post'], 'admin/profile', 'Auth::profile'); 

});`
