### ISSUE TITLE
Missing Config files

### ISSUE THREAD

**Issue by bernardshib** [GeekLabsUK/SimpleAuth#6]
Nice job Team,
I am just testing this. The Config files seem to be missing e.g. The /app/config/Email as well as the one for the database etc.

**Comment by GeekLabsUK** [comment]
The only config files included with SimpleAuth are Auth.php and an example Routes.php file. All other config files are part of your codeigniter 4 installation. 

Ensure you have a fresh install of codeigniter before importing the Simple Auth files
